name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull repo
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag flask_app:$(date +%s)
      - name: Test Docker Image
        run: docker run flask_app:$(date +%s) echo 'Executing tests...'
      - name: List Docker Images
        run: docker images

